---
title: "Εργαστήριο -- Πολυωνυμική παλινδρόμηση"
subtitle: ""
author: "Αλέξανδρος Ρέκκας"
date: "2025-12-11"
format:
  revealjs:
    theme: [default, custom.scss]
    logo: logo.jpg
    footer: "Ποσοτικές Μέθοδοι | Παιδαγωγικό Τμήμα Νηπιαγωγών - ΠΔΜ"
    slide-number: c/t
    incremental: false
    transition: slide
    background-transition: fade
    highlight-style: monokai
    code-line-numbers: false
    preview-links: auto
    width: 1280
    height: 720
    include-in-header:
      - text: |
          <style>
          .reveal mjx-mtext {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif !important;
            font-style: normal !important;
          }
          </style>
knitr:
  opts_chunk:
    fig.width: 10
    fig.height: 6
    dev: "svglite"
execute:
  echo: false
lang: el
---


# Ανακεφαλαίωση

## Το πρόβλημα

**Ερευνητικό Ερώτημα:**  
Ποιοι παράγοντες επηρεάζουν το είδος της φροντίδας που δεν προέρχεται από τους γονείς
(`primary_non_parental`);

## Το πρόβλημα

Τα δεδομένα μας (`sample_child.csv`):

- `child_gender`: Φύλο.
- `socioeconomic_status`: Κοινωνικο-οικονομικό επίπεδο.
- `mother_education`: Το μορφωτικό επίπεδο της μητέρας.
- `father_education`: Το μορφωτικό επίπεδο του πατέρα.

## Βήμα 1: Εισαγωγή δεδομένων

Ανοίξτε το αρχείο sample_child.csv στο Jamovi.

\


**ΠΡΟΣΟΧΗ**  
στους τύπους μεταβλητών!

## Βήμα 2: Απλή πολυωνυμική παλινδρόμηση

**Ερώτημα:**  
Επηρεάζει η κοινωνικο-οικονομική κατάσταση το είδος της φροντίδας που λαμβάνει το παιδί και δεν προέρχεται από τους
γονείς;

\

1. Tab: Analyses -> Regression -> N-Outcomes
2. Dependent Variable: `primary_non_parental`.
3. Covariates (συνεχείς): `socioeconomic_status`.

## Βήμα 2: Απλή λογιστική παλινδρόμηση

Τι κοιτάμε:

- Ποια είναι η τιμή της παραμέτρου της κοινωνικο-οικονομικής κατάστασης;
- Ποιο είναι το odds ratio για την κοινωνικο-οικονομική κατάσταση;
- P-value: Είναι στατιστικά σημαντική η σχέση;
- **Ποιες είναι οι πιθανότητες για μία τιμή της κοινωνικο-οικονομικής κατάστασης;**

## Βήμα 3: Πολλαπλή πολυωνυμική παλινδρόμηση

**Ερώτημα:** Ποιο είναι το μοντέλο της πολυωνυμικής παλινδρόμησης, αν λάβουμε υπόψη:

- Το φύλο
- Την κοινωνικο-οικονομική κατάσταση
- Το μορφωτικό επίπεδο της μητέρας
- Το μορφωτικό επίπεδο του πατέρα


## Βήμα 3: Πολλαπλή πολυωνυμική παλινδρόμηση

Τι κοιτάμε:

- Πώς ερμηνεύουμε τον συντελεστή του `mother_education`, κρατώντας τις
  υπόλοιπες μεταβλητές σταθερές;

## Βήμα 4: Έλεγχος υποθέσεων

**Ερώτημα:** Χρειάζεται να συμπεριλάβουμε το φύλο στο μοντέλο πολυωνυμικής
παλινδρόμησης, αν έχουμε ήδη συμπεριλάβει όλες τις υπόλοιπες μεταβλητές;

\

Εξακριβώστε την ισοδυναμία του πίνακα _Omnibus Likelihood Ratio Tests_ και της
γνωστής διαδικασίας για την αξιολόγηση μοντέλων (Model Builder).

## Βήμα 4: Σύγκριση Μοντέλων

**Ερώτημα:**  
Προσφέρουν κάτι παραπάνω τα μορφωτικά επίπεδα του πατέρα και της μητέρας, αν ήδη
ξέρουμε το φύλο και την κοινωνικο-οικονομική κατάσταση;

