---
format: typst
lang: el
---

```{=typst}
#set text(font: "Noto Serif", lang: "el")
#show link: set text(fill: blue)
#let tbox(title, body) = rect(fill: luma(240), stroke: 1pt + gray, radius: 6pt, inset: 10pt)[
  #text(weight: "bold")[#title]
  #v(5pt)
  #body
]

#set list(indent: 18pt)
#set enum(indent: 18pt)
#set page(
  numbering: "1 / 1",
  number-align: center,
  margin: (x: 2.3cm, y: 2cm)
)

#align(center)[
  #text(size: 16pt, weight: "bold")[2η ΕΡΓΑΣΙΑ]
  #v(8pt)
  #text(size: 12pt)[ΜΑΘΗΜΑ: Ποσοτικές Μέθοδοι]
]

#v(12pt)
```


**Ημερομηνία Παράδοσης:** 05/02/2026

## Περιγραφή μεταβλητών

**Στόχος** της παρούσας εργασίας είναι η μελέτη της σχολικής ετοιμότητας και της κοινωνικής συμπεριφοράς των παιδιών στο νηπιαγωγείο. 

Έχετε στη διάθεσή σας **προσομοιωμένα** δεδομένα 450 μαθητών νηπιαγωγείου. Οι
μεταβλητές που καταγράφονται είναι:

- **htks:** Βαθμολογία στη δοκιμασία "Κεφάλι-Πόδια-Γόνατα-Ώμοι"
  (head-toes-knees-shoulders). Η δοκιμασία αυτή χρησιμοποιείται για να
  αξιολογήσει την αυτορρύθμιση των παιδιών. 
- **peabody:** Βαθμολογία στην ελληνική προσαρμογή του Peabody Picture
  Vocabulary Test για. Η διαδικασία αυτή χρησιμοποιείται για την αξιολόγηση της
  λεκτικής ικανότητας των παιδιών.
- **age:** Η ηλικία του παιδιού σε μήνες.
- **family_ses:** Κατηγοριοποίηση με βάση το επάγγελμα των γονέων (εργατική,
  μεσαία, διευθυντική/επιστημονική).
- **school_type:** Ο τύπος του νηπιαγωγείου (δημόσιο, ιδιωτικό, πειραματικό).
- **sex:** Το φύλο του παιδιού (άρρεν, θήλυ).
- **bilingual:** Ύπαρξη δεύτερης γλώσσας στο σπίτι πέρα από τα ελληνικά. Σκοπός
  της μέτρησης της συγκεκριμένης μεταβλητής είναι η αξιολόγηση της πιθανότητας
  παραπομπής των παιδιών μεταναστών σε δομές υποστήριξης και συμβουλευτικής.

Οι εξαρτημένες μεταβλητές που θα μοντελοποιηθούν είναι:

- **conflict_strategy:** Η προσέγγιση του παιδιού στην σύγκρουση (διαπραγμάτευση, απόσυρση, σύγκρουση).
- **school_readiness:** Η σχολική ετοιμότητα του παιδιού (χαμηλή, μέτρια, υψηλή).
- **kedasy_referral:** Η παραπομπή του παιδιού σε ΚΕΔΑΣΥ (ναι, όχι).

##  Εργασίες

### Μέρος 1: Αντίδραση στην περίπτωση διαφωνίας

1. Να εκτελέσετε μία πολυωνυμική λογιστική παλινδρόμηση για την εκτίμηση των
   πιθανοτήτων ένα παιδί να αντιδράσει σε μία διαφωνία (σύγκρουση) με
   διαπραγμάτευση (επίπεδο αναφοράς), επιθετικότητα ή υποχώρηση. Οι ανεξάρτητες
   μεταβλητές που θα χρησιμοποιήσετε είναι οι htks, peabody, age, family_ses,
   sex και school_type.
2. Επηρεάζει το φύλο την αντίδραση με επιθετικότητα αντί για διαπραγμάτευση; Αν
   ναι, ποιο φύλο φαίνεται να έχει μεγαλύτερες πιθανότητες να αντιδράσει με
   επιθετικότητα;
3. Να συγκρίνετε τις πιθανότητες για κάθε μία από τις δυνατές αντιδράσεις σε
   περίπτωση διαφωνίας για δύο παιδιά τα οποία έχουν ίδια ηλικία (60 μήνες),
   ίδια βαθμολογία Peabody (100), ίδια επίδοση στην αξιλόγηση htks (45),
   προέρχονται και τα δύο από εργατική οικογένεια και πηγαίνουν σε δημόσιο
   σχολείο. Όμως, το ένα είναι αγόρι και το άλλο είναι κορίτσι.
4. Ο υπολογισμός του htks και του τεστ Peabody χρειάζεται αξιολόγηση από
   εξειδικευμένους εκπαιδευτικούς, επομένως δεν είναι πάντα εφικτός. Ένα μοντέλο
   λογιστικής πολυωνυμικής παλινδρόμησης χωρίς τις μεταβλητές αυτές θα μπορούσε
   να είναι εξίσου χρήσιμο, απαλλάσσοντας έτσι την ανάγκη πραγματοποίησης
   κοστοβόρων τεστ;

### Μέρος 2: Σχολική ετοιμότητα

1. Να εκτελέσετε μία διατάξιμη λογιστική παλινδρόμηση (ordinal logistic
   regression) με εξαρτημένη μεταβλητή τη σχολική ετοιμότητα (school_readiness)
   και με ανεξάρτητες μεταβλητές τις htks, peabody, age, family_ses, school_type
   και sex.
2. Ποιοι παράγοντες επηρεάζουν θετικά και ποιοι αρνητικά τη σχολική ετοιμότητα;
   Πώς το καταλάβατε;
3. Όπως και στο προηγούμενο ερώτημα, θα μπορούσαμε να χρησιμοποιήσουμε ένα
   μοντέλο χωρίς τις μεταβλητές htks και peabody με εξίσου καλή επίδοση;
4. Να συγκρίνετε τις πιθανότητες δύο παιδιών να χαρακτηρίζονται από υψηλή
   σχολική ετοιμότητα αν έχουν ίδια ηλικία (60 μήνες), ίδια βαθμολογία Peabody
   (100), ίδια επίδοση στην αξιλόγηση htks (45), προέρχονται και τα δύο από
   εργατική οικογένεια και πηγαίνουν σε δημόσιο σχολείο. Όμως, το ένα είναι
   αγόρι και το άλλο είναι κορίτσι.

### Μέρος 3: Παραπομπή σε ΚΕΔΑΣΥ

1. Να εκτελέσετε μία διωνυμική λογιστική παλινδρόμηση για την πρόβλεψη της
   πιθανότητας παραπομπής ενός παιδιού σε ΚΕΔΑΣΥ. Ως ανεξάρτητες μεταβλητές να
   χρησιμοποιήσετε τις htks, peabody, age, family_ses, school_type, sex και
   bilingual.
2. Να εξηγήσετε το συντελεστή και το odds ratio για τη μεταβλητή bilingual.
3. Χρειάζεται να προσθέσουμε τη νέα μεταβλητή bilingual στο μοντέλο αν έχουμε
   ήδη προσθέσει και όλες τις μεταβλητές που χρησιμοποιήσαμε στα προηγούμενα
   ερωτήματα;
4. Να συγκρίνετε τις πιθανότητες παραπομπής δύο παιδιών με τα ίδια
   χαρακτηριστικά (ηλικία 60 μηνών, βαθμολογία Peabody 100, επίδοση htks ίση με
   45, προέρχονται από εργατική οικογένεια, πηγαίνουν σε δημόσιο σχολείο, είναι
   και τα δύο κορίτσια) εκτός από τη διγλωσσία.
